name: CI workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim   
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install nose

      - name: Lint with Flake8
        run: |
          flake8 .

      - name: Run unit test with nose
        run: |
          nosetests -v --with-spec --spec-color --with-coverage --cover-package=app

